import { UnitType } from './constants.js';

/** Data-driven unit definitions — sprite paths resolved by AssetLoader */
export const UNIT_DEFS = Object.freeze({
  [UnitType.chauncey]: {
    sprite: 'sprite.png',
    sWidth: 56,
    sHeight: 56,
    speed: 2,
    life: 10,
    strength: 1,
    range: 0.5,
    isMobile: true,
    animate: {
      up: { sy: 168 },
      down: { sy: 0 },
      left: { sy: 56 },
      right: { sy: 112 },
      attack: { sy: 224 },
      dizzy: { sy: 336 },
      die: { sy: 280 },
    },
  },
  [UnitType.hordeling1]: {
    sprite: 'horde1.png',
    sWidth: 56,
    sHeight: 56,
    speed: 12,
    life: 1,
    strength: 1,
    range: 0.5,
    isMobile: true,
    animate: {
      up: { sy: 168 },
      down: { sy: 0 },
      left: { sy: 56 },
      right: { sy: 112 },
      die: { sy: 224 },
      attack: { sy: 280 },
    },
  },
  [UnitType.hordeling2]: {
    sprite: 'horde2.png',
    sWidth: 56,
    sHeight: 56,
    speed: 6,
    life: 1,
    strength: 1,
    range: 0.5,
    isMobile: true,
    animate: {
      up: { sy: 168 },
      down: { sy: 0 },
      left: { sy: 56 },
      right: { sy: 112 },
      die: { sy: 224 },
      attack: { sy: 280 },
    },
  },
  [UnitType.hordeling3]: {
    sprite: 'horde3.png',
    sWidth: 112,
    sHeight: 112,
    speed: 22,
    life: 10,
    strength: 2,
    range: 0.5,
    bulk: 0.5,
    isMobile: true,
    animate: {
      up: { sy: 336 },
      down: { sy: 0 },
      left: { sy: 112 },
      right: { sy: 224 },
      die: { sy: 448 },
      attack: { sy: 560 },
    },
  },
  [UnitType.hordeling4]: {
    sprite: 'horde4.png',
    sWidth: 56,
    sHeight: 56,
    speed: 14,
    life: 3,
    strength: 1,
    range: 0.5,
    isMobile: true,
    hasFireball: true,
    spellRange: 30,
    animate: {
      up: { sy: 0 },
      down: { sy: 65 },
      left: { sy: 65 },
      right: { sy: 0 },
      die: { sy: 278 },
      attack: { sy: 135 },
      castSpell: { sy: 135 },
    },
  },
  [UnitType.hordelingDragon]: {
    sprite: 'hordeDragon.png',
    sWidth: 80,
    sHeight: 80,
    speed: 12,
    life: 3,
    strength: 1,
    range: 0.5,
    isMobile: true,
    animate: {
      down: { sy: 0 },
      land: { sy: 80 },
      attack: { sy: 160 },
      die: { sy: 160 },
    },
  },
  [UnitType.guard]: {
    sprite: 'guard.png',
    sWidth: 56,
    sHeight: 53,
    speed: 8,
    life: 3,
    strength: 1,
    range: 0.5,
    isMobile: false,
    animate: {
      up: { sy: 53 },
      down: { sy: 0 },
      left: { sy: 106 },
      right: { sy: 159 },
      attack: { sy: 212 },
      die: { sy: 265 },
    },
  },
  [UnitType.patrolGuard]: {
    sprite: 'guard.png',
    sWidth: 56,
    sHeight: 53,
    speed: 4,
    life: 3,
    strength: 1,
    range: 0.5,
    isMobile: true,
    animate: {
      up: { sy: 53 },
      down: { sy: 0 },
      left: { sy: 106 },
      right: { sy: 159 },
      attack: { sy: 212 },
      die: { sy: 265 },
    },
  },
  [UnitType.arrow]: {
    sprite: 'arrow.png',
    sWidth: 35,
    sHeight: 40,
    speed: 2,
    life: 1,
    strength: 1,
    range: 0.2,
    isMobile: true,
    animate: {
      up: { sx: 0, sy: 0 },
      down: { sx: 147, sy: 36 },
      right: { sx: 0, sy: 40 },
      left: { sx: 135, sy: 120 },
      upleft: { sx: 65, sy: 90 },
      upright: { sx: 70, sy: 0 },
      downleft: { sx: 65, sy: 120 },
      downright: { sx: 70, sy: 40 },
    },
  },
  [UnitType.knight]: {
    sprite: 'knight.png',
    sWidth: 56,
    sHeight: 73,
    speed: 3,
    life: 4,
    strength: 1,
    range: 0.5,
    isMobile: true,
    animate: {
      up: { sy: 73 },
      down: { sy: 0 },
      left: { sy: 146 },
      right: { sy: 219 },
      attack: { sy: 292 },
      die: { sy: 365 },
    },
  },
  [UnitType.archer]: {
    sprite: 'archer.png',
    sWidth: 56,
    sHeight: 56,
    speed: 12,
    life: 2,
    strength: 1,
    range: 3,
    isMobile: false,
    animate: {
      down: { sx: 0, sy: 0 },
      attack: { sy: 120, syLeft: 175 },
      die: { sy: 70 },
    },
  },
  [UnitType.catapult]: {
    sprite: 'catapult.png',
    sWidth: 100,
    sHeight: 100,
    speed: 14,
    life: 10,
    strength: 1,
    range: 5,
    minRange: 2,
    multiProjectileAngle: 20,
    isMobile: false,
    animate: {
      down: { sx: 0, sy: 0 },
      attack: { sy: 0, syLeft: 100 },
      die: { sy: 200 },
    },
  },
  [UnitType.fireball]: {
    sprite: 'fireball.png',
    sWidth: 38,
    sHeight: 38,
    speed: 2,
    life: 1,
    strength: 4,
    range: 1,
    isMobile: true,
    animate: {
      up: { sx: 228, sy: 0 },
      down: { sx: 76, sy: 0 },
      right: { sx: 0, sy: 0 },
      left: { sx: 152, sy: 0 },
      upleft: { sx: 190, sy: 0 },
      upright: { sx: 266, sy: 0 },
      downleft: { sx: 228, sy: 0 },
      downright: { sx: 38, sy: 0 },
      attack: { sy: 38 },
    },
  },
  [UnitType.shamanFireball]: {
    sprite: 'fireball.png',
    sWidth: 38,
    sHeight: 38,
    speed: 2,
    life: 1,
    strength: 2,
    range: 1,
    isMobile: true,
    animate: {
      up: { sx: 228, sy: 0 },
      down: { sx: 76, sy: 0 },
      right: { sx: 0, sy: 0 },
      left: { sx: 152, sy: 0 },
      upleft: { sx: 190, sy: 0 },
      upright: { sx: 266, sy: 0 },
      downleft: { sx: 228, sy: 0 },
      downright: { sx: 38, sy: 0 },
      attack: { sy: 38 },
    },
  },
});
